export const EntityTypes = Object.freeze({
  ADF: "Approved Deposit Fund",
  ARF: "ARPA Regulated Fund",
  COP: "Co-operative",
  CUT: "Corporate Unit Trust",
  DES: "Deceased Estate",
  DIP: "Diplomatic/Consulate Body or High Commission",
  FGA: "FGA",
  FGD: "FGD",
  FHS: "First Home Saver Accounts Trust",
  FPT: "Family Partnership",
  FSA: "FSA",
  GOV: "GOV",
  IND: "Individual/Sole Trader",
  JVT: "JVT",
  LOC: "LOC",
  LPT: "Limited Partnership",
  NRF: "Non-Regulated Superannuation Fund",
  OIE: "Other Incorporated Entity",
  PDF: "Pooled Development Fund",
  PRV: "Australian Private Company",
  PST: "Pooled Superannuation Trust",
  PTR: "Other Partnership",
  PTT: "Public Trading Trust",
  PUB: "Australian Public Company",
  SMF: "ATO Regulated Self-Managed Superannuation Fund",
  SSA: "State Government APRA Regulated Public Sector Fund",
  STA: "STA",
  STR: "Strata-title",
  SUP: "Super Fund",
  TER: "TER",
  TRT: "Other Trust",
  UIE: "Other Unincorporated Entity",
  CGT: "Commonwealth Government Trust",
  LGA: "Local Government Statutory Authority",
  LGC: "Local Government Company",
  LGE: "Local Government Entity",
  LGP: "Local Government Partnership",
  LGS: "LGS",
  LGT: "Local Government Trust",
  SGA: "State Government Statutory Authority",
  SGC: "State Government Company",
  SGE: "State Government Entity",
  SGP: "State Government Partnership",
  SGS: "SGS",
  SGT: "State Government Trust",
  TGA: "Territory Government Statutory Authority",
  TGC: "TGC",
  TGE: "Territory Government Entity",
  TGP: "Territory Government Partnership",
  TGS: "TGS",
  TGT: "Territory Government Trust",
  CGA: "Commonwealth Government Statutory Authority",
  CGC: "Commonwealth Government Company",
  CGE: "Commonwealth Government Entity",
  CGP: "Commonwealth Government Partnership",
  CGS: "Commonwealth Government Super Fund",
  CCB: "Commonwealth Government Public Company",
  CCC: "Commonwealth Government Co-operative",
  CCL: "Commonwealth Government Limited Partnership",
  CCN: "Commonwealth Government Other Unincorporated Entity",
  CCO: "Commonwealth Government Other Incorporated Entity",
  CCP: "Commonwealth Government Pooled Development Fund",
  CCR: "Commonwealth Government Private Company",
  CCS: "Commonwealth Government Strata Title",
  CCT: "Commonwealth Government Public Trading Trust",
  CCU: "Commonwealth Government Public Trading Trust",
  CMT: "Cash Management Trust",
  CSA: "Commonwealth Government APRA Regulated Public Sector Fund",
  CSP: "Commonwealth Government APRA Regulated Public Sector Scheme",
  CSS: "Commonwealth Government Non-Regulated Super Fund",
  CTC: "Commonwealth Government Cash Management Trust",
  CTD: "Commonwealth Government Discretionary Services Management Trust",
  CTF: "Commonwealth Government Fixed Trust",
  CTH: "Commonwealth Government Hybrid Trust",
  CTI: "Commonwealth Government Discretionary Investment Trust",
  CTL: "Commonwealth Government Listed Public Unit Trust",
  CTQ: "Commonwealth Government Unlisted Public Unit Trust",
  CTT: "Commonwealth Government Discretionary Trading Trust",
  CTU: "Commonwealth Government Fixed Unit Trust",
  DIT: "Discretionary Investment Trust",
  DST: "Discretionary Services Management Trust",
  DTT: "Discretionary Trading Trust",
  FUT: "Fixed Unit Trust",
  FXT: "Fixed Trust",
  HYT: "Hybrid Trust",
  LCB: "Local Government Public Company",
  LCC: "Local Government Co-operative",
  LCL: "Local Government Limited Partnership",
  LCN: "Local Government Other Unincorporated Entity",
  LCO: "Local Government Other Incorporated Entity",
  LCP: "Local Government Pooled Development Fund",
  LCR: "Local Government Private Company",
  LCS: "Local Government Strata Title",
  LCT: "Local Government Public Trading Trust",
  LCU: "Local Government Public Trading Unit Trust",
  LSA: "Local Government APRA Regulated Public Sector Fund",
  LSP: "Local Government APRA Regulated Public Sector Scheme",
  LSS: "Local Government Non-Regulated Super Fund",
  LTC: "Local Government Cash Management Trust",
  LTD: "Local Government Discretionary Services Management Trust",
  LTF: "Local Government Fixed Trust",
  LTH: "Local Government Hybrid Trust",
  LTI: "Local Government Discretionary Investment Trust",
  LTL: "Local Government Listed Public Unit Trust",
  LTQ: "Local Government Unlisted Public Unit Trust",
  LTT: "Local Government Discretionary Investment Trust",
  LTU: "Local Government Fixed Unit Trust",
  NPF: "APRA Regulated Non-Public Offer Fund",
  POF: "APRA Regulated Public Offer Fund",
  PQT: "Unlisted Public Unit Trust",
  PUT: "Listed Public Unit Trust",
  SAF: "Small APRA Regulated Fund",
  SCB: "State Government Public Company",
  SCC: "State Government Co-operative",
  SCL: "State Government Limited Partnership",
  SCN: "State Government Other Unincorporated Entity",
  SCO: "State Government Other Incorporated Entity",
  SCP: "State Government Pooled Development Fund",
  SCR: "State Government Private Company",
  SCS: "State Government Strata Title",
  SCT: "State Government Public Trading Trust",
  SCU: "State Government Corporate Unit Trust",
  SSP: "State Government APRA Regulated Public Sector Scheme",
  SSS: "State Government Non-Regulated Super Fund",
  STC: "State Government Cash Management Trust",
  STD: "State Government Discretionary Services Management Trust",
  STF: "State Government Fixed Trust",
  STH: "State Government Hybrid Trust",
  STI: "State Government Discretionary Investment Trust",
  STL: "State Government Listed Public Unit Trust",
  STQ: "State Government Unlisted Public Unit Trust",
  STT: "State Government Discretionary Trading Trust",
  STU: "State Government Fixed Unit Trust",
  TCB: "Territory Government Public Company",
  TCC: "Territory Government Co-operative",
  TCL: "Territory Government Limited Partnership",
  TCN: "Territory Government Other Unincorporated Entity",
  TCO: "Territory Government Other Incorporated Entity",
  TCP: "Territory Government Pooled Development Fund",
  TCR: "Territory Government Private Company",
  TCS: "Territory Government Strata Title",
  TCT: "Territory Government Public Trading Trust",
  TCU: "Territory Government Corporate Unit Trust",
  TSA: "Territory Government APRA Regulated Public Sector Fund",
  TSP: "Territory Government APRA Regulated Public Sector Scheme",
  TSS: "Territory Government Non-Regulated Super Fund",
  TTC: "Territory Government Cash Management Trust",
  TTD: "Territory Government Discretionary Services Management Trust",
  TTF: "Territory Government Fixed Trust",
  TTH: "Territory Government Hybrid Trust",
  TTI: "Territory Government Discretionary Investment Trust",
  TTL: "Territory Government Listed Public Unit Trust",
  TTQ: "Territory Government Unlisted Public Unit Trust",
  TTT: "Territory Government Discretionary Trading Trust",
  TTU: "Territory Government Fixed Unit Trust",
});

export const StateNames = Object.freeze({
  AAT: "Australian Antarctic Territory",
  QLD: "Queensland",
  ACT: "Australian Capital Territory",
  NSW: "New South Wales",
  WA: "Western Australia",
  VIC: "Victoria",
  NT: "Northern Territory",
  TAS: "Tasmania",
  SA: "South Australia",
});

export const NameEnum = Object.freeze({
  MN: "MN",
  DGR: "DGR",
  LGL: "LGL",
  TRD: "TRD",
  OTN: "OTN",
  BN: "BN",
});

export enum StatusType {
  cancelled = "CAN",
  active = "ACT",
}

export enum StateEnum {
  AAT = "AAT",
  QLD = "QLD",
  ACT = "ACT",
  NSW = "NSW",
  WA = "WA",
  VIC = "VIC",
  NT = "NT",
  TAS = "TAS",
  SA = "SA",
}

export enum EntityTypeInd {
  ADF = "ADF",
  ARF = "ARF",
  COP = "COP",
  CUT = "CUT",
  DES = "DES",
  DIP = "DIP",
  FGA = "FGA",
  FGD = "FGD",
  FHS = "FHS",
  FPT = "FPT",
  FSA = "FSA",
  GOV = "GOV",
  IND = "IND",
  JVT = "JVT",
  LOC = "LOC",
  LPT = "LPT",
  NRF = "NRF",
  OIE = "OIE",
  PDF = "PDF",
  PRV = "PRV",
  PST = "PST",
  PTR = "PTR",
  PTT = "PTT",
  PUB = "PUB",
  SMF = "SMF",
  SSA = "SSA",
  STA = "STA",
  STR = "STR",
  SUP = "SUP",
  TER = "TER",
  TRT = "TRT",
  UIE = "UIE",
  CGT = "CGT",
  LGA = "LGA",
  LGC = "LGC",
  LGE = "LGE",
  LGP = "LGP",
  LGS = "LGS",
  LGT = "LGT",
  SGA = "SGA",
  SGC = "SGC",
  SGE = "SGE",
  SGP = "SGP",
  SGS = "SGS",
  SGT = "SGT",
  TGA = "TGA",
  TGC = "TGC",
  TGE = "TGE",
  TGP = "TGP",
  TGS = "TGS",
  TGT = "TGT",
  CGA = "CGA",
  CGC = "CGC",
  CGE = "CGE",
  CGP = "CGP",
  CGS = "CGS",
  CCB = "CCB",
  CCC = "CCC",
  CCL = "CCL",
  CCN = "CCN",
  CCO = "CCO",
  CCP = "CCP",
  CCR = "CCR",
  CCS = "CCS",
  CCT = "CCT",
  CCU = "CCU",
  CMT = "CMT",
  CSA = "CSA",
  CSP = "CSP",
  CSS = "CSS",
  CTC = "CTC",
  CTD = "CTD",
  CTF = "CTF",
  CTH = "CTH",
  CTI = "CTI",
  CTL = "CTL",
  CTQ = "CTQ",
  CTT = "CTT",
  CTU = "CTU",
  DIT = "DIT",
  DST = "DST",
  DTT = "DTT",
  FUT = "FUT",
  FXT = "FXT",
  HYT = "HYT",
  LCB = "LCB",
  LCC = "LCC",
  LCL = "LCL",
  LCN = "LCN",
  LCO = "LCO",
  LCP = "LCP",
  LCR = "LCR",
  LCS = "LCS",
  LCT = "LCT",
  LCU = "LCU",
  LSA = "LSA",
  LSP = "LSP",
  LSS = "LSS",
  LTC = "LTC",
  LTD = "LTD",
  LTF = "LTF",
  LTH = "LTH",
  LTI = "LTI",
  LTL = "LTL",
  LTQ = "LTQ",
  LTT = "LTT",
  LTU = "LTU",
  NPF = "NPF",
  POF = "POF",
  PQT = "PQT",
  PUT = "PUT",
  SAF = "SAF",
  SCB = "SCB",
  SCC = "SCC",
  SCL = "SCL",
  SCN = "SCN",
  SCO = "SCO",
  SCP = "SCP",
  SCR = "SCR",
  SCS = "SCS",
  SCT = "SCT",
  SCU = "SCU",
  SSP = "SSP",
  SSS = "SSS",
  STC = "STC",
  STD = "STD",
  STF = "STF",
  STH = "STH",
  STI = "STI",
  STL = "STL",
  STQ = "STQ",
  STT = "STT",
  STU = "STU",
  TCB = "TCB",
  TCC = "TCC",
  TCL = "TCL",
  TCN = "TCN",
  TCO = "TCO",
  TCP = "TCP",
  TCR = "TCR",
  TCS = "TCS",
  TCT = "TCT",
  TCU = "TCU",
  TSA = "TSA",
  TSP = "TSP",
  TSS = "TSS",
  TTC = "TTC",
  TTD = "TTD",
  TTF = "TTF",
  TTH = "TTH",
  TTI = "TTI",
  TTL = "TTL",
  TTQ = "TTQ",
  TTT = "TTT",
  TTU = "TTU",
}

export enum MainOrLegal {
  MAIN = "MAIN",
  LEGAL = "LEGAL",
}

export enum NameType {
  MN = "MN",
  DGR = "DGR",
  LGL = "LGL",
  TRD = "TRD",
  OTN = "OTN",
  BN = "BN",
}
